### ISSUE TITLE
Didn't investigate why, but this script freezes my Xcode's GUI debugger

### ISSUE THREAD

**Issue by nathanlanza** [bsmt/lldbinit#1]
Thought my Xcode was bugged or some work-related configuration was bugging up my Xcode lldb until I just guessed to comment out the line that sources this. Sure enough, Xcode went back to work like normal. Obviously not crucial or anything, just a heads up.

**Comment by bsmt** [comment]
Good. I don't use LLDB/OS X anymore so I can't really investigate. I wrote this probably 5 years ago so it's not surprising that it causes problems now.

**Comment by nathanlanza** [comment]
Blah, sorry I meant to post this on gdbinit/lldbinit -_-. Sorry
